### ISSUE TITLE
Flood fill 

### ISSUE THREAD

**Issue by defart** [anthonynsimon/bild#25]
Hi, i'd like to contribute with a flood fill algorithm, would that fit within the project?

**Comment by anthonynsimon** [comment]
Sure, contributions are more than welcome. Simply create a new package within the project, something like "paint" for example, as there might be new functions we can add under that category.

**Comment by anthonynsimon** [comment]
Looks good so far, thanks for adding tests one time. Will review it in a second.

**Comment by anthonynsimon** [comment]
I just merged your pull request with the fixes and added an example image to the README.
