### ISSUE TITLE
Add Translation functionality

### ISSUE THREAD

**Issue by lloeki** [anthonynsimon/bild#26]
Apply a translation transformation that operates similar to the rotation one with regards to the viewport/canvas (i.e fill blanks, crop out-of-canvas data).

It's exceedingly useful when thinking about processing that applies steps in an automated pipeline, such as rotate -> zoom -> translate -> crop.

Use case example: http://codepen.io/lloeki/pen/BzoyNJ

**Comment by anthonynsimon** [comment]
You're right, it's quite a useful function. I went ahead and added a basic implementation with tests, checkout the pull request I referenced.

You can also see an example [here](https://github.com/anthonynsimon/bild/tree/add-translate#translate)
