### ISSUE TITLE
Inserting an image

### ISSUE THREAD

**Issue by dreddsa5dies** [anthonynsimon/bild#38]
How can I insert a cut image using a library?

**Comment by anthonynsimon** [comment]
Hey, you could use one of the blend modes to achieve this. For example, the `normal` blend mode simply puts the foreground on top of the background without any operation. Like so:

```go
import "github.com/anthonynsimon/bild/blend"

result := blend.Normal(background, foreground)
```

![](https://anthonynsimon.github.io/projects/bild/normal.jpg)

**Comment by dreddsa5dies** [comment]
Thank you very much
