### ISSUE TITLE
Trim to edges

### ISSUE THREAD

**Issue by DAddYE** [anthonynsimon/bild#39]
Hi!

Thanks for this amazing library!

I saw that `effect` pkg support both Sobel and EdgeDetection. 

It is possible to use one of them to trim to the edges?

Basically I have an image, I want to find the edges and trim the images close to its borders.

Thanks so much!

**Comment by anthonynsimon** [comment]
Hi, it is certainly possible to achieve that, but none of the current operations do that out of the box. The missing part is the function to calculate the area to be trimmed based on the edges detected.

**Comment by nf-brentsaner** [comment]
@DAddYE If you still need this, I just wrote a function that trims/crops all surrounding transparency; I'd imagine you could adapt it for your needs.

It's not the greatest because it iterates pixel-by-pixel instead of dispatching e.g. interpolated rows to goroutines and re-assembling or something for REALLY LARGE images, but it should be fine for most use cases.

```go
func trimTransparent(img image.Image) (trimmed image.Image) {

	var x int
	var y int
	var a uint32
	var bnds image.Rectangle = img.Bounds()
	// min* being initially set to ...Max and vice versa
	// is INTENTIONAL. weird, but intentional.
	var minX int = bnds.Max.X
	var maxX int = bnds.Min.X
	var minY int = bnds.Max.Y
	var maxY int = bnds.Min.Y

	for y = bnds.Min.Y; y < bnds.Max.Y; y++ {
		for x = bnds.Min.X; x < bnds.Max.X; x++ {
			if _, _, _, a = img.At(x, y).RGBA(); a > 0 {
				if x < minX {
					minX = x
				}
				if x > maxX {
					maxX = x
				}
				if y < minY {
					minY = y
				}
				if y > maxY {
					maxY = y
				}
			}
		}
	}

	if minX >= maxX || minY >= maxY {
		// No alpha found.
		trimmed = img
	} else {
		trimmed = transform.Crop(
			img,
			image.Rectangle{
				Min: image.Point{
					X: minX,
					Y: minY,
				},
				Max: image.Point{
					X: maxX + 1,
					Y: maxY + 1,
				},
			},
		)
	}

	return
}
```
