### ISSUE TITLE
Allow destruction

### ISSUE THREAD

**Issue by QuentinDanjou** [anthonynsimon/bild#43]
What do you think about adding the possibility to allow original image destruction in spite of using clone.AsRGBA() ?
It can result in better performance.

**Comment by anthonynsimon** [comment]
After reviewing the changes required for this, a lot of functionality is based on the assumption that the image changes are immutable, which would make this change quite difficult to introduce into the codebase. 

Will be closing the issue for now until it becomes a performance bottleneck.
