### ISSUE TITLE
watermark functionality

### ISSUE THREAD

**Issue by rajat-mangla** [anthonynsimon/bild#56]
Is there any way, I can have the above functionality using this library

**Comment by anthonynsimon** [comment]
I think it should be possible via one of the blending modes, i.e.:

```go
import "github.com/anthonynsimon/bild/blend"

opacity := 0.25
result := blend.Opacity(mainImage, watermark, opacity)
```

https://godoc.org/github.com/anthonynsimon/bild/blend#Opacity
