### ISSUE TITLE
[Feature]Perlin noise 

### ISSUE THREAD

**Issue by roz3x** [anthonynsimon/bild#73]
I have added few files in my local repo , that enables noise package to give images with coherent noise .Yes , using  parallel implementation , like as of other noise functions  . I wanted to know about  
1. should i commit directly to master branch .
2. is it necessary to write tests for noise functions

**Comment by anthonynsimon** [comment]
Hey, thanks for your interest in contributing.

1. You should create a GitHub PR first to have your work merged into the
repo.

2. Yes, it’s ok to not write a test in this case.

Looking forward to your PR!

**Comment by roz3x** [comment]
hey ! thanks for responding . here is the link to my repo .(https://github.com/roz3x/bild) .. please let  me know , if this follows your projects guidelines .. <3

**Comment by roz3x** [comment]
i also added a code snippet to readme.md file and the working example is in main.go file

**Comment by roz3x** [comment]
hey thanks , would you like to merge the pr , with the master ?? please tell me before or if you do so . 

regards

**Comment by anthonynsimon** [comment]
Hey, I added a review on the PR #74
