### ISSUE TITLE
Strongly recommended add func about translate normal pic to round pic,it is very useful when create some picture. 

### ISSUE THREAD

**Issue by rhettli** [anthonynsimon/bild#86]
**Origin avatar:**
![image](https://user-images.githubusercontent.com/26317003/91114451-85b8ae80-e6ba-11ea-98aa-7b6c673710c2.png)

**And translate 1:**
![image](https://user-images.githubusercontent.com/26317003/91114426-776a9280-e6ba-11ea-8ca7-9f4d6d88637e.png)

**And translate 2:**
![image](https://user-images.githubusercontent.com/26317003/91114444-80f3fa80-e6ba-11ea-8399-c5c9c8336b98.png)

**Comment by ou-bing** [comment]
@rhettli hello, how did you finally generate round pic ？
